### ISSUE TITLE
Add a link from the planned recipe view back to the library view for that same recipe

### ISSUE THREAD

**Issue by switzerb** [folded-ear/gobrennas-client#119]
It would be handy, while looking at the planned recipe, to reference the original recipe "template". Often the planned recipe has undergone edits that the larger recipe has not.

**Comment by barneyb** [comment]
W/in `PlannedRecipeController`, the `lo` variable's value has an `ingredientId` property which is the library recipe the planned recipe was created from. It's not part of the `RecipeFromPlanItem` type, because its never mattered, but probably should be. The `aggregateId` might also be interesting, so if you've opened a planned subrecipe, you can navigate back to the top-level planned recipe, especially if you've moved the subrecipe out from under its parent on the plan, so you can bucket it separately or what have you.
