### ISSUE TITLE
opening a recipe flashes 404 while loading

### ISSUE THREAD

**Issue by barneyb** [folded-ear/gobrennas-client#71]
The fix for #68 was defective, in that it treats a not-yet-loaded recipe as missing as well, so the 404 is flashed up briefly, instead of the spinner. It works correctly for the deleted case.

Three cases:
1. opening a recipe which is present in the apollo cache
2. opening a recipe which is not in the apollo cache, but does exist
3. opening a recipe which is not in the apollo cache, and doesn't exist in the database

In the first case, the recipe should render directly.

In the second, a spinner should show until the recipe is retrieved, and then it should render. Currently it shows 404 when it should show a spinner.

In the third, a spinner should show until the recipe is confirmed to not exist in the database, then it should show 404.

The second and third cases should work correctly when opening from a library search _and_ by entering a URL directly in the location bar.

**Comment by barneyb** [comment]
I also noticed the GraphQL query doesn't raise an error when a non-existent recipe is requested, it returns `null`. The equivalent REST endpoint raises `NoResultException`.

**Comment by switzerb** [comment]
Interestingly, I am unable to delete a recipe and getting a foreign key constraint error in checking the use case. I will file a bug report and continue investigating at a later time:

<img width="1145" alt="image" src="https://github.com/folded-ear/gobrennas-client/assets/363095/74dacce0-e83e-4ec1-bd7d-7d7dc797d040">

**Comment by barneyb** [comment]
I think that means the recipe is used as an ingredient in another recipe (e.g., meatballs w/in spaghetti and meatballs). You can just enter any non-existent ID to replicate the "deleted recipe" use case. It didn't have to previously exist.

**Comment by switzerb** [comment]
So, the first thing that I did was to change the `fetchPolicy` of the `useQuery` call to `network-only` so that I could consistently reproduce use case two, where the flash of 404 was occuring instead of the loader. I also confirmed that when a recipe does not exist in the database, we get a `null` value back from the `useQuery` method for that recipe. 

So the flash of 404 makes sense because in this case, both an existing recipe that has not loaded yet and a deleted recipe both have `null` results. The fix needs to distinguish between these two states.

In the first use case, I did not notice any defects in loading so that is working as intended.

For both the second and third use cases, there needs to be a way to know that there will *never* be a return value for a particular recipe. In my opinion, this belongs on the server side and returning a null value for a recipe is incorrect behavior. I am going to try and implement that solution. If a `NoResultException` is thrown from the server instead of returning a null, then it should be a simple matter of throwing a `404` when an error is returned and a loader while it is in a `null` state.
